//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acesso
    {
        public int Id { get; set; }
        public int IdFuncao { get; set; }
        public int IdPerfil { get; set; }
    
        public virtual Funcao Funcao { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
