//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BancoDocumento
    {
        public int Id { get; set; }
        public int IdBanco { get; set; }
        public int IdTipoDocumento { get; set; }
        public bool Obrigatorio { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
