//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Divida
    {
        public int Id { get; set; }
        public int IdBanco { get; set; }
        public int IdProposta { get; set; }
        public decimal SaldoDevedor { get; set; }
        public Nullable<decimal> ValorParcela { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Proposta Proposta { get; set; }
    }
}
