//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcao
    {
        public Funcao()
        {
            this.Acessos = new HashSet<Acesso>();
            this.FuncoesInferiores = new HashSet<Funcao>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<int> IdFuncaoSuperior { get; set; }
        public string Link { get; set; }
    
        public virtual ICollection<Acesso> Acessos { get; set; }
        public virtual ICollection<Funcao> FuncoesInferiores { get; set; }
        public virtual Funcao FuncaoSuperior { get; set; }
    }
}
