//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTelefone
    {
        public TipoTelefone()
        {
            this.TelefonesProposta = new HashSet<TelefoneProposta>();
            this.TelefonesUsuario = new HashSet<TelefoneUsuario>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<TelefoneProposta> TelefonesProposta { get; set; }
        public virtual ICollection<TelefoneUsuario> TelefonesUsuario { get; set; }
    }
}
